### ISSUE TITLE
Sometimes the tgz archive created in Windows, when unpacking, gives an error

### ISSUE THREAD

**Issue by SergeyMi37** [intersystems/ipm#284] opened 2021-11-23 08:20 UTC
Sometimes the tgz archive created in Windows, when unpacking, gives an error

set st=##class(%ZPM.PackageManager.Developer.Archive).Extract("D:\!\a1\useroles.tgz", "d:\!\a2\" , .pOutput)

w st
0 2  -<NOTOPEN>zMoveToEnd+10^%Stream.FileBinary.1ö USERë'^zMoveToEnd+10^%Stream.FileBinary.1^1'd^zCopyFrom+19^%Stream.FileBinary.1^1'd^zCopyFrom+15^%Stream.FileBinary.1^2&d^zCopyFrom+8^%Stream.FileBinary.1^2)e^zCopyFromAndSave+2^%Stream.Object.1^1.d^zExtractTo+12^%ZPM.Utils.FileBinaryTar.1^12d^zExtractStream+64^%ZPM.Utils.FileBinaryTar.1^10e^zExtractFile+10^%ZPM.Utils.FileBinaryTar.1^19e^zExtract+28^%ZPM.PackageManager.Developer.Archive.1^1!e^zprompt+64^%ZAPM.ext.zapp.1^1!x^zprompt+64^%ZAPM.ext.zapp.1^1 d^ZAPM^%ZLANGC00^2d^^^0

**Comment by isc-rkuszews** [comment] 2023-09-08 15:21
Does this still happen?  If so, can you attach more info about which packages or info about the machines where it happens?

**Comment by isc-tleavitt** [comment] 2023-09-08 15:50
I'd wager this is a duplicate of https://github.com/intersystems/ipm/issues/416 (or rather #416 was a duplicate of this); closing as duplicate.

**Closed by isc-tleavitt** 2023-09-08 15:50 UTC
Labels: bug
