### ISSUE TITLE
Add support for wildcards for folder items, e.g. DFI

### ISSUE THREAD

**Issue by evshvarov** [intersystems/ipm#622] opened 2024-11-07 23:51 UTC
There are projects which contain several hundred pivots and dashboards organized by folders.
Currently, module.xml should have a resource for each folder item.
Please add the support of resources that will allow you to collect the whole folder of folder items or even wildcards in names.

**Comment by isc-tleavitt** [comment] 2024-11-08 13:51
@evshvarov this is a duplicate of #381 which I still intend to see happen.

**Closed** 2024-11-08 13:51 UTC
