### ISSUE TITLE
Add Warning when delete/update package that have dependent packages

### ISSUE THREAD

**Issue by nsolov** [intersystems/ipm#401] opened 2023-05-19 06:29 UTC
Now a package can be deleted without any warnings, when other packages depends on this package

**Comment by isc-tleavitt** [comment] 2024-03-15 17:36
This is a duplicate of an old one (#58) - closing this one in favor of the older (to say "we should have done this a long time ago")

**Closed by isc-tleavitt** 2024-03-15 17:36 UTC
Labels: bug
