### ISSUE TITLE
IPM/ZPM Deleted on IRIS Upgrade?

### ISSUE THREAD

**Issue by DodgeDeBoulet** [intersystems/ipm#421] opened 2023-06-23 11:41 UTC
Yesterday I updated from Health Connect 2023.1.0.229.0 to 2023.1.0.235.1 on 4  servers (2 mirrored pairs). These servers also have **git-source-control** installed (via ZPM). This is a Windows installation on Windows Server 2019 Standard 1809. 

All was working fine prior to the update, but after completion I received the following errors when I signed into Studio:
```
[Iris ODBC][State : S1000][Native Code 400]
[C:\INTERSYSTEMS\HEALTHSHARE\BIN\CStudio.exe]
[SQLCODE: <-400>:<Fatal error occurred>]
[Error: <<CLASS DOES NOT EXIST>OnMenuItem+2^SourceControl.Git.Extension.1 *%ZPM.PackageManager.Core.Singleton>]
[Location: <SPFetch>]

class '%Studio.SourceControl.Interface', method 'UserAction': <CLASS DOES NOT EXIST> 150 GetStatus+1^SourceControl.Git.Extension.1 %ZPM.PackageManager.Core.Singleton

class '%Library.RoutineMgr', method 'Exists': <CLASS DOES NOT EXIST> 150 OnBeforeLoad+1^SourceControl.Git.Extension.1 %ZPM.PackageManager.Core.Singleton

class '%Library.RoutineMgr', method 'Exists': <CLASS DOES NOT EXIST> 150 OnBeforeLoad+1^SourceControl.Git.Extension.1 %ZPM.PackageManager.Core.Singleton

class '%Library.RoutineMgr', method 'Exists': <CLASS DOES NOT EXIST> 150 OnBeforeLoad+1^SourceControl.Git.Extension.1 %ZPM.PackageManager.Core.Singleton
```
I re-installed IPM and the errors no longer occurred.

**Comment by isc-tleavitt** [comment] 2024-03-15 15:30
This will be resolved with the merge (including rename to %IPM) from the v1 branch.

Root cause is https://docs.intersystems.com/iris20241/csp/docbook/Doc.View.cls?KEY=RCOS_appx_identifiers#RCOS_appx_identifiers_irissys - it's expected that IPM (with classes in the %ZPM package) must be reinstalled after upgrade.

**Comment by isc-tleavitt** [comment] 2024-08-27 16:30
Closing issues fixed in v1 branch for cleaner bookkeeping.

**Closed by isc-tleavitt** 2024-08-27 16:30 UTC
Labels: bug
