### ISSUE TITLE
Missing changes from HS Package Manager during merge

### ISSUE THREAD

**Issue by isc-kiyer** [intersystems/ipm#510] opened 2024-06-25 14:11 UTC
The following features did not get into the combined IPM during the merge of HealthShare package manager code into IPM;

1. Modifier -showSource for the zpm "list" command which lists the root of the installed module on the local file system.
2. Summary view of zpm "help" command which gives a short summary of all commands and only detailed description when help is run for an individual command.

**Comment by isc-tleavitt** [comment] 2024-06-25 14:14
@isc-kiyer thank you!

**Comment by isc-shuliu** [comment] 2024-07-08 19:10
@isc-kiyer @isc-tleavitt 

The 1st issue is being addressed in PR #518 . 

Somehow I couldn't reproduce the 2nd issue. When running `zpm "help"` I get a high-level summary of commands. When running `zpm "help repo"`, I get a detailed spec of `repo` command. I am testing on the `v1` branch.

**Comment by isc-shuliu** [comment] 2024-07-24 13:50
@isc-tleavitt 
So after discussion with Keshav, we have identified 2 missing features that's available in HS package manger
* The `help` command output can be more succinct (addressed by #520)
* List installed packages by repo name (addressed by #521)

**Comment by isc-shuliu** [comment] 2024-07-25 18:23
Closing since #520, #521, and #518 are merged

**Closed by isc-shuliu** 2024-07-25 18:23 UTC
Labels: bug
